### ISSUE TITLE
GoLive Runbook

### ISSUE THREAD

**Issue by nc-andreashaller** [hlxsites/netcentric#105]
- [x] content review done
- [x] get final "go" - <responsible TBD>
- [x] activate robots.txt & sitemap.xml - #110 
- [x] change configuration in CDN - @nc-andreashaller + OPS
- [x] activate CDN config in Franklin config sheet

**Comment by mhaack** [comment]
Linking Franklin Go-Live checklist https://www.hlx.live/docs/go-live-checklist

**Comment by nc-andreashaller** [comment]
Go live successful 1st Dec ~3:45pm CET.
