### ISSUE TITLE
People profile sheet for blog authors

### ISSUE THREAD

**Issue by mhaack** [hlxsites/netcentric#13]
We want to manage the blog authors via some Google Sheet. Blog posts will only store a reference to the author. Author details (images, job title, description) should be loaded dynamically.

- [x] setup & publish the people profile sheet

**Comment by dkuntze** [comment]
@mhaack all that is left here is to populate the sheet with the blog authors.

**Comment by mhaack** [comment]
Assigned to @jonatan-lledo-netcentric who will provide an export containing all the authors.

**Comment by mhaack** [comment]
Closed with #95

**Comment by mhaack** [comment]
Author profiles are available via https://main--netcentric--hlxsites.hlx.live/profiles/query-index.json

**Comment by mhaack** [comment]
Author profiles are available via https://main--netcentric--hlxsites.hlx.live/profiles/query-index.json
