### ISSUE TITLE
Link at the end of the blog post doesn't show as a button

### ISSUE THREAD

**Issue by alexcarol** [hlxsites/netcentric#138]
Expected:
 https://www.netcentric.biz/insights/2022/09/content-at-scale
![image](https://user-images.githubusercontent.com/1713440/204814627-417b58f3-a13d-494d-b7be-8c8e8e46ec3f.png)

Actual:
https://main--netcentric--hlxsites.hlx.page/insights/2022/09/content-at-scale
![image](https://user-images.githubusercontent.com/1713440/204814851-4b5a2e06-4a15-4396-bcd5-2c85d95290d9.png)

**Comment by mhaack** [comment]
Issue is a combination of wrong content format (section with center missing) and section not working.
