### ISSUE TITLE
[Blog Post Page] implement sidebar

### ISSUE THREAD

**Issue by mhaack** [hlxsites/netcentric#14]
Implement sidebar for blogpost page displaying the author(s) and social share links.

**Comment by hannessolo** [comment]
Similar code:  https://main--lazard--hlxsites.hlx.page/research-insights/lazard-insights/state-of-play 
https://github.com/hlxsites/lazard/blob/d5572f584dfdc4f76942464113cc13e642d1fad4/blocks/articles-sidebar/articles-sidebar.css#L194
