### ISSUE TITLE
Add LiveUX (RUM) collector script

### ISSUE THREAD

**Issue by verlok** [hlxsites/netcentric#23]
Hello,

as a web performance consultant, I’d like to add our LiveUX (a RUM tool) collector script to the website, so that I will be able monitor performance in the field.

The script to add is already present in the current version of the website, and it is:

```html
<script 
  src="https://liveux.cnwebperformance.biz/collector/collector.min.js?id=webperf-netcentric" 
  defer 
  crossorigin="anonymous"></script>
```

More information on LiveUX can be found [here](https://projects.netcentric.biz/wiki/display/LUX/Getting+started+with+LiveUX).

As per [Markus message on Slack](https://ncchat.slack.com/archives/C03K480JSF4/p1668686711177609?thread_ts=1668683246.777669&cid=C03K480JSF4), this would need to be put in [the `scripts/delayed.js` file](https://github.com/hlxsites/netcentric/blob/main/scripts/delayed.js).

Thank you

**Comment by verlok-cn** [comment]
@kmurugulla checked and verified!
