### ISSUE TITLE
[Block] Implement Card with "icon-text" style

### ISSUE THREAD

**Issue by mhaack** [hlxsites/netcentric#38]
Original: https://www.netcentric.biz/who-we-are.html
Franklin: https://docs.google.com/document/d/18v60MnckEhak1ykRMH10FdcapkntIQSKxQQX_cJWJEw/edit#

Sample:
![Screenshot 2022-11-21 at 15 09 13](https://user-images.githubusercontent.com/2643450/203075651-7f70cbdf-963a-48fa-8c43-ce4ce49ac8c3.png)

**Comment by Buuhuu** [comment]
@mhaack, here is another occurrence of cards:

- https://www.netcentric.biz/
- https://docs.google.com/document/d/1eOeXsP1phS99jjeXD6nrPSLAeEx1iDZAZFwxR6aFJZ8/edit

I assume both should work and share the same block, hence this being part of the scope of this ticket too?
