### ISSUE TITLE
Add data-attributes for LiveUX

### ISSUE THREAD

**Issue by verlok** [hlxsites/netcentric#72]
We need a hidden element in the DOM with some data-attributes so we can access some data. In the future, we will require variables in the global JS workspace, but for the first golive this is the solution we need.

The data attributes can be in **any tag of the page**, like a hidden `div`.

```html
<div class="hidden" data-...></div>
```

Here are the data attributes we need.

| attribute name            | opt/mand  | type   | level   | e.g.                                                        | notes                                                                                         |
| ------------------------- | --------- | ------ | ------- | ----------------------------------------------------------- | --------------------------------------------------------------------------------------------- |
| `data-wp-version-name`    | mandatory | string | website | `"franklin"`                                                | we should have "aem" on the current website (we don’t, at the moment)                         |
| `data-wp-page-type`       | mandatory | string | page    | `"home"`, `"article"`, `"case-study"`… (names are invented) | can be the name of the template defined in Franklin, if any                                   |
| `data-wp-http-status`     | mandatory | string | page    | `"200"`, `"404" `                                           | it’s fine if it’s "static", we need just to distinguish the 404 (and other errors?) pages     |
| `data-wp-page-cookie`     | optional  | string | page    | `"accepted"`, `"C001,C002"`, `"not-accepted"`               | this should be changed using JS after the Cookie layer is dismissed                           |

This was extensively discussed in [this conversation](https://ncchat.slack.com/archives/C03K480JSF4/p1669124755714029).

**Comment by mhaack** [comment]
For the `data-wp-page-cookie` this needs to be linked with #12

**Comment by ramboz** [comment]
The proposed approach we discussed was leveraging the global and page metadata to achieve this, so authors can easily inject the props and update those if needed.

And then we take a few lines of JS to replicate the meta props on the body or main element.

Only exception would be the cookie value as @mhaack pointed out

**Comment by nc-andreashaller** [comment]
Could you align those infos with the dataLayer Analytics uses? @verlok please talk to Mauricio if there are such values already available there. Especially data-wp-page-type smells like something Analytics would need too.

**Comment by meryllblanchet** [comment]
Draft instrumentation on the main div here: https://github.com/hlxsites/netcentric/tree/72-data-attributes-live-ux
See on https://72-data-attributes-live-ux--netcentric--hlxsites.hlx.page/drafts/mblanche/who-we-are.

**Comment by verlok-cn** [comment]
Thanks @meryllblanchet, that works!

Would you be able to update it also on the [404 page](https://72-data-attributes-live-ux--netcentric--hlxsites.hlx.page/drafts/mblanche/who-we-arr), or is it something we need to do on NC's side?

**Comment by verlok-cn** [comment]
Also @meryllblanchet can you please open a PR?

**Comment by verlok-cn** [comment]
@meryllblanchet? The golive is tomorrow at 3PM, can you open a PR?

**Comment by meryllblanchet** [comment]
Hello @verlok , apologies for having missed you here. Will raise a PR tomorrow morning as I am also adding the support for the 404 html.
Let's sync-up on Slack, I will briefly show you the setup on the authoring side.

**Comment by meryllblanchet** [comment]
Actually @verlok , I updated the PR that has been opened by @mhaack . Please check https://github.com/hlxsites/netcentric/pull/143.
