### ISSUE TITLE
Column Variations

### ISSUE THREAD

**Issue by Buuhuu** [hlxsites/netcentric#78]
Columns (2):
- layout 25-75 (https://www.netcentric.biz/insights/netcentric-podcast.html)
- layout 33-66 (https://www.netcentric.biz/what-we-do/bernstein-methodology.html)
- layout 66-33 (https://www.netcentric.biz/our-industries.html)
- layout 75-25

Styling
- border in-between (https://www.netcentric.biz/our-industries.html)
- border top-right (https://www.netcentric.biz/what-we-do/digital-strategy.html)
- border top-left (https://www.netcentric.biz/insights/netcentric-podcast.html)

Heading Colors
- heading-dark-blue (https://www.netcentric.biz/our-industries/financial-services-insurance.html)
- headling-dark-plum (https://www.netcentric.biz/our-industries.html)

On https://www.netcentric.biz/what-we-do.html

> As Cognizant’s Adobe center of excellence, our...

Columns

> Our Offerings

Columns (layout 25-75)

> Our latest Podcast or 

Columns (layout 33-66, border top-left) 

> Success cases & Whitepapers

Columns (layout 66-33, border in-between)

**Comment by mhaack** [comment]
Collection of the different variants https://main--netcentric--hlxsites.hlx.live/drafts/mhaack/layouts
