### ISSUE TITLE
Cookie Banner does now work

### ISSUE THREAD

**Issue by mhaack** [hlxsites/netcentric#90]
Users choice on the cookie banner is not respected. I get the cookie banner on every page load.

**Comment by nc-andreashaller** [comment]
I think this is actually being cause by the domain not being registered with OneTrust, but I am also not 100% sure so worth investigating.

**Comment by mhaack** [comment]
@nc-andreashaller should we build in a switch to disable it on localhost (for dev) and hlx.page URLs. At least for now?

**Comment by nc-andreashaller** [comment]
good idea, is it integrated directly or via Launch right now?

**Comment by mhaack** [comment]
Via Launch. I suggest we only load the launch scripts on prod domain.

**Comment by mhaack** [comment]
Seams to work now.
